export function seed(knex) {
	const table = 'states'

	return Promise.all([
		knex(table).del(),

		knex(table).insert({ abbreviation: 'AL', name: 'Alabama', country_id: 1 }),
		knex(table).insert({ abbreviation: 'AK', name: 'Alaska', country_id: 1 }),
		knex(table).insert({ abbreviation: 'AZ', name: 'Arizona', country_id: 1 }),
		knex(table).insert({ abbreviation: 'AR', name: 'Arkansas', country_id: 1 }),
		knex(table).insert({ abbreviation: 'CA', name: 'California', country_id: 1 }),
		knex(table).insert({ abbreviation: 'CO', name: 'Colorado', country_id: 1 }),
		knex(table).insert({ abbreviation: 'CT', name: 'Connecticut', country_id: 1 }),
		knex(table).insert({ abbreviation: 'DE', name: 'Delaware', country_id: 1 }),
		knex(table).insert({ abbreviation: 'FL', name: 'Florida', country_id: 1 }),
		knex(table).insert({ abbreviation: 'GA', name: 'Georgia', country_id: 1 }),
		knex(table).insert({ abbreviation: 'HI', name: 'Hawaii', country_id: 1 }),
		knex(table).insert({ abbreviation: 'ID', name: 'Idaho', country_id: 1 }),
		knex(table).insert({ abbreviation: 'IL', name: 'Illinois', country_id: 1 }),
		knex(table).insert({ abbreviation: 'IN', name: 'Indiana', country_id: 1 }),
		knex(table).insert({ abbreviation: 'IA', name: 'Iowa', country_id: 1 }),
		knex(table).insert({ abbreviation: 'KS', name: 'Kansas', country_id: 1 }),
		knex(table).insert({ abbreviation: 'KY', name: 'Kentucky', country_id: 1 }),
		knex(table).insert({ abbreviation: 'LA', name: 'Louisiana', country_id: 1 }),
		knex(table).insert({ abbreviation: 'ME', name: 'Maine', country_id: 1 }),
		knex(table).insert({ abbreviation: 'MD', name: 'Maryland', country_id: 1 }),
		knex(table).insert({ abbreviation: 'MA', name: 'Massachusetts', country_id: 1 }),
		knex(table).insert({ abbreviation: 'MI', name: 'Michigan', country_id: 1 }),
		knex(table).insert({ abbreviation: 'MN', name: 'Minnesota', country_id: 1 }),
		knex(table).insert({ abbreviation: 'MS', name: 'Mississippi', country_id: 1 }),
		knex(table).insert({ abbreviation: 'MO', name: 'Missouri', country_id: 1 }),
		knex(table).insert({ abbreviation: 'MT', name: 'Montana', country_id: 1 }),
		knex(table).insert({ abbreviation: 'NE', name: 'Nebraska', country_id: 1 }),
		knex(table).insert({ abbreviation: 'NV', name: 'Nevada', country_id: 1 }),
		knex(table).insert({ abbreviation: 'NH', name: 'New Hampshire', country_id: 1 }),
		knex(table).insert({ abbreviation: 'NJ', name: 'New Jersey', country_id: 1 }),
		knex(table).insert({ abbreviation: 'NM', name: 'New Mexico', country_id: 1 }),
		knex(table).insert({ abbreviation: 'NY', name: 'New York', country_id: 1 }),
		knex(table).insert({ abbreviation: 'NC', name: 'North Carolina', country_id: 1 }),
		knex(table).insert({ abbreviation: 'ND', name: 'North Dakota', country_id: 1 }),
		knex(table).insert({ abbreviation: 'OH', name: 'Ohio', country_id: 1 }),
		knex(table).insert({ abbreviation: 'OK', name: 'Oklahoma', country_id: 1 }),
		knex(table).insert({ abbreviation: 'OR', name: 'Oregon', country_id: 1 }),
		knex(table).insert({ abbreviation: 'PA', name: 'Pennsylvania', country_id: 1 }),
		knex(table).insert({ abbreviation: 'RI', name: 'Rhode Island', country_id: 1 }),
		knex(table).insert({ abbreviation: 'SC', name: 'South Carolina', country_id: 1 }),
		knex(table).insert({ abbreviation: 'SD', name: 'South Dakota', country_id: 1 }),
		knex(table).insert({ abbreviation: 'TN', name: 'Tennessee', country_id: 1 }),
		knex(table).insert({ abbreviation: 'TX', name: 'Texas', country_id: 1 }),
		knex(table).insert({ abbreviation: 'UT', name: 'Utah', country_id: 1 }),
		knex(table).insert({ abbreviation: 'VT', name: 'Vermont', country_id: 1 }),
		knex(table).insert({ abbreviation: 'VA', name: 'Virginia', country_id: 1 }),
		knex(table).insert({ abbreviation: 'WA', name: 'Washington', country_id: 1 }),
		knex(table).insert({ abbreviation: 'WV', name: 'West Virginia', country_id: 1 }),
		knex(table).insert({ abbreviation: 'WI', name: 'Wisconsin', country_id: 1 }),
		knex(table).insert({ abbreviation: 'WY', name: 'Wyoming', country_id: 1 }),
		knex(table).insert({ abbreviation: 'DC', name: 'Washington DC', country_id: 1 })
	])
}
