/** Declaration file generated by dts-gen */
declare module 'i/lib/methods' {
	export function camelize(
		lowerCaseAndUnderscoredWord: string,
		firstLetterInUppercase: string,
	): string

	export function classify(tableName: string): string

	export function dasherize(underscoredWord: string): string

	export function demodulize(classNameInModule: string): string

	export function foreign_key(
		className: string,
		separateClassNameAndIdWithUnderscore: string,
	): string

	export function humanize(lowerCaseAndUnderscoredWord: string): string

	export function ordinalize(number: string): string

	export function pluralize(word: string): string

	export function singularize(word: string): string

	export function tableize(className: string): string

	export function titleize(word: string): string

	export function uncountability(word: string): string

	export function underscore(camelCasedWord: string): string
}
