exports.seed = (knex, Promise) ->
	table = knex('states')

	return Promise.join(
		knex('states').del(),

		knex('states').insert({ abbreviation: 'AL', name: 'Alabama' }),
		knex('states').insert({ abbreviation: 'AK', name: 'Alaska' }),
		knex('states').insert({ abbreviation: 'AZ', name: 'Arizona' }),
		knex('states').insert({ abbreviation: 'AR', name: 'Arkansas' }),
		knex('states').insert({ abbreviation: 'CA', name: 'California' }),
		knex('states').insert({ abbreviation: 'CO', name: 'Colorado' }),
		knex('states').insert({ abbreviation: 'CT', name: 'Connecticut' }),
		knex('states').insert({ abbreviation: 'DE', name: 'Delaware' }),
		knex('states').insert({ abbreviation: 'FL', name: 'Florida' }),
		knex('states').insert({ abbreviation: 'GA', name: 'Georgia' }),
		knex('states').insert({ abbreviation: 'HI', name: 'Hawaii' }),
		knex('states').insert({ abbreviation: 'ID', name: 'Idaho' }),
		knex('states').insert({ abbreviation: 'IL', name: 'Illinois' }),
		knex('states').insert({ abbreviation: 'IN', name: 'Indiana' }),
		knex('states').insert({ abbreviation: 'IA', name: 'Iowa' }),
		knex('states').insert({ abbreviation: 'KS', name: 'Kansas' }),
		knex('states').insert({ abbreviation: 'KY', name: 'Kentucky' }),
		knex('states').insert({ abbreviation: 'LA', name: 'Louisiana' }),
		knex('states').insert({ abbreviation: 'ME', name: 'Maine' }),
		knex('states').insert({ abbreviation: 'MD', name: 'Maryland' }),
		knex('states').insert({ abbreviation: 'MA', name: 'Massachusetts' }),
		knex('states').insert({ abbreviation: 'MI', name: 'Michigan' }),
		knex('states').insert({ abbreviation: 'MN', name: 'Minnesota' }),
		knex('states').insert({ abbreviation: 'MS', name: 'Mississippi' }),
		knex('states').insert({ abbreviation: 'MO', name: 'Missouri' }),
		knex('states').insert({ abbreviation: 'MT', name: 'Montana' }),
		knex('states').insert({ abbreviation: 'NE', name: 'Nebraska' }),
		knex('states').insert({ abbreviation: 'NV', name: 'Nevada' }),
		knex('states').insert({ abbreviation: 'NH', name: 'New Hampshire' }),
		knex('states').insert({ abbreviation: 'NJ', name: 'New Jersey' }),
		knex('states').insert({ abbreviation: 'NM', name: 'New Mexico' }),
		knex('states').insert({ abbreviation: 'NY', name: 'New York' }),
		knex('states').insert({ abbreviation: 'NC', name: 'North Carolina' }),
		knex('states').insert({ abbreviation: 'ND', name: 'North Dakota' }),
		knex('states').insert({ abbreviation: 'OH', name: 'Ohio' }),
		knex('states').insert({ abbreviation: 'OK', name: 'Oklahoma' }),
		knex('states').insert({ abbreviation: 'OR', name: 'Oregon' }),
		knex('states').insert({ abbreviation: 'PA', name: 'Pennsylvania' }),
		knex('states').insert({ abbreviation: 'RI', name: 'Rhode Island' }),
		knex('states').insert({ abbreviation: 'SC', name: 'South Carolina' }),
		knex('states').insert({ abbreviation: 'SD', name: 'South Dakota' }),
		knex('states').insert({ abbreviation: 'TN', name: 'Tennessee' }),
		knex('states').insert({ abbreviation: 'TX', name: 'Texas' }),
		knex('states').insert({ abbreviation: 'UT', name: 'Utah' }),
		knex('states').insert({ abbreviation: 'VT', name: 'Vermont' }),
		knex('states').insert({ abbreviation: 'VA', name: 'Virginia' }),
		knex('states').insert({ abbreviation: 'WA', name: 'Washington' }),
		knex('states').insert({ abbreviation: 'WV', name: 'West Virginia' }),
		knex('states').insert({ abbreviation: 'WI', name: 'Wisconsin' }),
		knex('states').insert({ abbreviation: 'WY', name: 'Wyoming' }),
		knex('states').insert({ abbreviation: 'DC', name: 'Washington DC' })
	)
